### ISSUE TITLE
Add plugin framework for output types - not just CSV

### ISSUE THREAD

**Issue by millerjp** [dagwieers/dstat#101]
It would be useful to support plugins to enable development of different output types - not just CSV. 

For example, I want to run a performance test accross a very large number of clusters and I may choose to stream this data out to somewhere else and analyse runtime rather than copy CSV files and ingest etc..

**Comment by scottchiefbaker** [comment]
What types of output would you be interested in?

**Comment by dagwieers** [comment]
If you look at the TODO list, people have suggested spreadsheet output (including graphs, just like iozone), syslog output (as a transport to centralize data), RRD output, and all sorts of formats to interface with existing infrastructure (mysql, etc...).

**Comment by millerjp** [comment]
@scottchiefbaker @dagwieers MQTT, Kafka etc.. - these would be great to integrate with.

**Comment by dpquigl** [comment]
This issue seems to have gone cold but has discussion happened with regards to this topic? I just got done writting a performance analysis script and dealing with the json output from fio was significantly easier to work with that the csv format dstat outputs.  Has anyone discussed a json output formation for dstat?
