### ISSUE TITLE
Negative values for disk read and write values in log file

### ISSUE THREAD

**Issue by log69** [dagwieers/dstat#61]
Command:

dstat -cmdn --output logfile.txt 60

Problem:

Negative numbers appeared in the read and write columns of the disk stat.

Expected result:

Never give negative values.

The log file:
https://gist.github.com/log69/7839547

Negative values are at line 789 and 807 in the disk read and write columns.

Another problem is that dstat reprints the headers from time to time in the log file, no matter whether I specify --noheaders parameter or not.

System:

Dstat 0.7.2
Kernel 3.8.0-34-generic
Python 2.7.4 (default, Sep 26 2013, 03:20:26) 
[GCC 4.7.3]
Terminal type: screen (color support)
Terminal size: 43 lines, 134 columns
Processors: 2
Pagesize: 4096
Clock ticks per secs: 100

**Comment by dagwieers** [comment]
These are counter-rollovers. Please read the documentation related to counter-rollovers.
This is less likely to occur on 64bit systems, but common on high-speed interfaces on 32bit systems.

**Comment by scottchiefbaker** [comment]
@dagwieers do we not compensate for counter rollovers? I've done it before, it's not that hard:

https://github.com/scottchiefbaker/perl-snmp-monitor/blob/master/snmp_int_watch.pl#L373

**Comment by dagwieers** [comment]
We don't. Theoretically with bonded 10Gbit interfaces you can have rollovers every few seconds. So if you have a larger window you can have multiple rollovers in a single time-frame. So if you start compensating, you hide this information with no guarantee or certainty, while if you leave that information in place it is up to the end-user to see how to process this information (either compensate or deem compensation impossible).

I would agree if you can do it correctly in 100% of the cases, but since we cannot be sure, I'd rather not. Besides thanks to 64bit counters this problem is dealt with properly on newer systems.
