### ISSUE TITLE
mix different types of values in one plugin

### ISSUE THREAD

**Issue by ecraven** [dagwieers/dstat#87]
Hello ;)

I've been playing around with a httpd (apache) plugin, I'd need to display byte values, integers and float values, all as different vars of one plugin. Is there a good way to achieve this?

Thanks, Peter

**Comment by dagwieers** [comment]
Yes, that's something I would like to have as well. Probably for a 0.8 release where we modify the plugin interface. The current implementation dates back from the inception of dstat and in hindsight it is a pretty poor implementation basically because we didn't know how it would be evolving.

Sometimes people only need individual counts, however most users prefer the plugin output in full. So changing this interface should include:

- A probe phase that returns a list of items
- A collection phase that simple adds values to a tree of values
- A display phase that prints (selected) items to screen
- A logging phase that logs (selected) items to a formatted file

Doing it this way other tools can hook into dstat and get counters in an efficient manner.
