### ISSUE TITLE
Documentation for steal CPU%

### ISSUE THREAD

**Issue by mattheworiordan** [dagwieers/dstat#90]
`dstat` is an amazing tool, however I frequently used to resort to `iostat` on our EC2 instances as `%steal` is a very important metric for us.

Looking at the [TODO](https://github.com/dagwieers/dstat/blob/master/TODO), it still says this needs to be added to `--cpu-adv` plugin, however running `dstat --cpu-adv` it is clear it is already implemented.

It would be great to update the docs so that people know this exists.
### Note for anyone reading this

The version of `dstat` available from `apt-get` or other Debian based installers does not support `--cpu-adv`, I had to `git clone` this repo and run the binary directly.

**Comment by scottchiefbaker** [comment]
@mattheworiordan we'd love a pull request for this. Sounds like you know more about `%steal` than I do anyway. If you update the docs I'll gladly merge it.

**Comment by dagwieers** [comment]
The TODO should probably be replaced by Github issues (as feature requests). However that means people won't see the TODO list in full (as part of the distribution) unless we automate this. And it makes us more dependant on Github and Github processes (which may be an advantage rather than a drawback).
