### ISSUE TITLE
--freespace allow to exclude(or whitelist) mount points

### ISSUE THREAD

**Issue by BenasPaulikas** [dagwieers/dstat#93]
For instance I only want to display "/" mountpoint size, I don't need /run or /dev mountpoints size

**Comment by scottchiefbaker** [comment]
@dagwieers is it possible to pass an option to a plugin? Ideally it would work something like this

```
# Show all mount points
dstat --all --freespace
```

or

```
# Show specific mount points
dstat --all --freespace /,/home
```

This has been a pain point for me also. I'll code up a pull request if you can assist me in figure out (in the freespace plugin) how to read the command line args for dstat. Are there any other plugins that do this I can use as a starting point.

**Comment by scottchiefbaker** [comment]
I had a slow morning so I taught myself enough python to solve this. The code is written and tested I just need a way to get the data IN to the plugin.

**Comment by dagwieers** [comment]
I don't think this is a good idea. It means that you always have to pass information to the option. If one would do `dstat --freespace --tcp` the freespace plugin will be supplied with the data `--tcp` and the tcp plugin will not be run. This will confuse people. If we want to pass information to plugins via the Dstat command-line, we will have to add additional options, which will make it very long and tedious to use. (e.g. `--freespace --freespace-mounts=/,/usr`).

Unless we want to implement ordered options so that one can do:

    `--freespace --opts=/,/usr --plugin2 --opts=1,2,3`

But this means that the order of the options is important, at least for `--opts=`, the order of the plugins already influences the order of shown counters, so the order has some meaning now already.

**Comment by dagwieers** [comment]
Let's continue the discussion at #107 !
